"""The humidifier template component."""

import logging
import os

from homeassistant.core import HomeAssistant

_LOGGER = logging.getLogger(__name__)

DOMAIN = "humidifier_template"

FRONTEND_DIR = "frontend"
FRONTEND_SCRIPT = "humidity-tile-buttons.js"
FRONTEND_URL_BASE = f"/{DOMAIN}_frontend"

_FRONTEND_KEY = f"{DOMAIN}_frontend_registered"


async def async_register_frontend(hass: HomeAssistant, version: str) -> None:
    """Serve the tile-buttons module and load it with the frontend.

    The built-in Climate, Home and Areas pages are generated by view strategies whose tiles get a
    feature from a fixed chain that has no humidity entry, so a humidifier tile carries no control.
    The module registers a custom card feature and attaches it to those tiles. Serving it from the
    integration rather than www/ means it ships and updates with this component, needs no
    configuration.yaml entry, and comes back on its own after a restart.

    Registration is idempotent and never fatal: without the module the entities still work, so a
    failure here is logged and setup continues.
    """
    if hass.data.get(_FRONTEND_KEY):
        return
    hass.data[_FRONTEND_KEY] = True

    try:
        from homeassistant.components.frontend import add_extra_js_url
        from homeassistant.components.http import StaticPathConfig

        source = os.path.join(os.path.dirname(__file__), FRONTEND_DIR)
        await hass.http.async_register_static_paths(
            [StaticPathConfig(FRONTEND_URL_BASE, source, cache_headers=False)]
        )
        # The version query defeats the frontend's long cache lifetime, so a new release of this
        # integration is actually fetched instead of served from a stale copy.
        add_extra_js_url(
            hass, f"{FRONTEND_URL_BASE}/{FRONTEND_SCRIPT}?v={version}"
        )
        _LOGGER.debug("Registered %s at %s", FRONTEND_SCRIPT, FRONTEND_URL_BASE)
    except Exception:  # noqa: BLE001 - never block entity setup on the frontend extra
        hass.data[_FRONTEND_KEY] = False
        _LOGGER.exception(
            "Could not register the %s frontend module; humidifier tiles will "
            "fall back to stock Home Assistant behaviour",
            DOMAIN,
        )
